number_1 = input("Введите первое число: ")
word_1 = input("Введите первое слово: ")
number_2 = input("Введите второе число: ")
word_2 = input("Введите второе слово: ")

print("Первое число: " + number_1)
print("Первое слово: " + word_1)
print("Второе число: " + number_2)
print("Второе слово: " + word_2)
print("Вы ввели: " + number_1 + " , " + word_1 + " , " + number_2 + " , " + word_2 + ".")